#!/usr/bin/env python
import os
import sys
import subprocess

from tider import RELOAD

cmd = ['python', os.path.join(os.path.dirname(__file__), 'tider.py')]
cmd += sys.argv[1:]
try:
    code = subprocess.call(cmd)
    if code == RELOAD:
        subprocess.call(sys.argv)
except KeyboardInterrupt:
    raise SystemExit()
