#!/usr/bin/env python
import os
import sys
import subprocess

from tider import RELOAD

cmd = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'tider.py')
cmd = ['python', cmd] + sys.argv[1:]
try:
    code = subprocess.call(cmd)
    if code == RELOAD:
        subprocess.call(sys.argv)
except KeyboardInterrupt:
    raise SystemExit()
